2020-11-03 22:26:10.255 INFO _internal - _log:  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2020-11-03 22:26:12.725 ERROR app - log_exception: Exception on /respuestas [GET]
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "api.py", line 60, in respuestas
    return jsonify(result),200
  File "C:\Python\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Python\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Python\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Python\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Python\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Row is not JSON serializable
2020-11-03 22:26:12.764 INFO _internal - _log: 127.0.0.1 - - [03/Nov/2020 22:26:12] "[35m[1mGET /respuestas HTTP/1.1[0m" 500 -
2020-11-03 22:27:09.104 INFO _internal - _log:  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2020-11-03 22:27:12.087 ERROR app - log_exception: Exception on /respuestas [GET]
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "api.py", line 64, in respuestas
    return jsonify(resp),200
  File "C:\Python\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Python\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Python\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Python\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Python\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Row is not JSON serializable
2020-11-03 22:27:12.091 INFO _internal - _log: 127.0.0.1 - - [03/Nov/2020 22:27:12] "[35m[1mGET /respuestas HTTP/1.1[0m" 500 -
2020-11-03 22:27:44.015 INFO _internal - _log:  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2020-11-03 22:27:45.644 INFO _internal - _log: 127.0.0.1 - - [03/Nov/2020 22:27:45] "[37mGET /respuestas HTTP/1.1[0m" 200 -
2020-11-03 22:28:38.626 INFO _internal - _log:  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2020-11-03 22:28:53.007 INFO _internal - _log: 127.0.0.1 - - [03/Nov/2020 22:28:53] "[37mGET /respuestas HTTP/1.1[0m" 200 -
2020-11-03 22:29:47.020 INFO _internal - _log:  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2020-11-03 22:29:50.966 INFO _internal - _log: 127.0.0.1 - - [03/Nov/2020 22:29:50] "[37mGET /respuestas HTTP/1.1[0m" 200 -
